version: 0.2

phases:
  build:
    commands:
      # 创建输出目录
      - mkdir -p output/scripts
      - mkdir -p output/static
      - mkdir -p output/config

      # 拷贝静态资源（保留 assets 子目录）
      - cp -r home/static/assets output/static/

      # 拷贝配置文件（如果有）
      - '[ -f deploy/nginx/config/nginx.conf ] && cp deploy/nginx/config/nginx.conf output/config/'

      # 拷贝 appspec 和 shell 脚本
      - cp deploy/nginx/appspec.yml output/
      - cp deploy/nginx/scripts/* output/scripts/

artifacts:
  files:
    - output/**/*
  discard-paths: no
