# Generated by Django 5.1.7 on 2025-04-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='feedback',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q1',
            field=models.TextField(default='', verbose_name='问题1：您对课程内容的满意度？'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q10',
            field=models.TextField(default='', verbose_name='问题10：未来还希望开设哪些主题？'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q2',
            field=models.TextField(default='', verbose_name='问题2：授课老师是否清晰易懂？'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q3',
            field=models.TextField(default='', verbose_name='问题3：学习节奏是否合适？'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q4',
            field=models.TextField(default='', verbose_name='问题4：课程材料是否充分？'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q5',
            field=models.TextField(default='', verbose_name='问题5：练习内容是否有帮助？'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q6',
            field=models.TextField(default='', verbose_name='问题6：您希望增加哪些内容？'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q7',
            field=models.TextField(default='', verbose_name='问题7：对本次课程的总体评分？'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q8',
            field=models.TextField(default='', verbose_name='问题8：参加该课程的动机？'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q9',
            field=models.TextField(default='', verbose_name='问题9：对组织方式的意见或建议？'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
