# Generated by Django 5.1.7 on 2025-04-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_submitted_at_surveyresponse_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='category',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='email',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='name',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='target',
            field=models.CharField(default='通用', max_length=100, verbose_name='调查对象'),
        ),
    ]
