# Generated by Django 5.1.7 on 2025-04-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_surveyresponse_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='target',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='课程类别'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
    ]
